
security:
  oauth2:
    client:
      clientId: 336970807211419
      clientSecret: 6f66650eed2151d763344ca1a4ebae7a
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
